### ISSUE TITLE
Attribute attribute 'Curve'Error: type object 'Bezier' has no

### ISSUE THREAD

**Issue by xentient** [torresjrjr/Bezier.py#1]
I have installed your module, wrote a short script to see if I could use it and Bingo! It works great and does what I need. I try all sorts of numbers, and it works fine with my PIL-based app. I copy the code to my project's development version, same code, same include, both the test script and main file run in the same environment, and with the same calling lines, the test file works fine but the main file reports the error message 

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\miche\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "D:\_DOCS\_CODE\ImProc\pxl_dialogs.py", line 3735, in sliderAfter1
    exec(sliderparam)
  File "<string>", line 1, in <module>
  File "D:\_DOCS\_CODE\ImProc\pxl_classesA.py", line 120800, in slider_1
    self.updateinput(10)
  File "D:\_DOCS\_CODE\ImProc\pxl_classesA.py", line 120790, in updateinput
    thickness, isFilled)
  File "D:\_DOCS\_CODE\ImProc\pxl_classesA.py", line 120954, in adjust
    curve1 = Bezier.Curve(t_points, fullshape) #............ Returns an array of coordinates.
AttributeError: type object 'Bezier' has no attribute 'Curve'

If I try again after this with my test file, no problem!!! The Bezier object has a Curve attribute,
 Can you think of something that would cause this?

**Comment by torresjrjr** [comment]
Hi, @xentient 

I wrote this project over two years ago, when my Python skills were poor, and haven't touched it since. Nevertheless, I'll try to help you out. I'm delighted to know someone has taken interest in this project.

Firstly, I should mention, all my main correspondence occurs over at my main hub at Sourcehut < https://sr.ht/~torresjrjr >. That is to say, I don't use GitHub anymore. I haven't moved this repo over to Sourcehut as I didn't regard as it important enough. Perhaps I should.

Now, as for your problem. It is perculiar. It's quite difficult to see where the problem lies without seeing the code or the development process. I can tell you're using Windows, which I'm familiar with.

Perhaps if I see the code, I might be able to help you out quicker. Is there a git repository I can view?

I'll take this opportunity to suggest a git repository hosted on Sourcehut < https://sourcehut.org/ >, which takes about 2 minutes to set up. Otherwise, a GitHub repository would suffice.

Happy to help
~b

**Comment by torresjrjr** [comment]
@xentient 

I've moved this repository to my Sourcehut account.
https://sr.ht/~torresjrjr/Bezier.py/

Any new commits will appear there.

**Comment by xentient** [comment]
Hey! Thanks for the quick response, I wasn't expecting that!
Yes it is a bizarre bug, I suspect it has to do with Python not correctly
killing the instance. I fixed it, sort of, by copying the code to my
file.It happens with Tkinter, which I use a lot, some instances of their
widgets remain in memory and when I call for a new one, points to an old
instantiation long gone and throws a bad pathname error. Last time I fixed
with specifically deleting the offending widgets.

_____________

*Michel Poisson*

**Comment by torresjrjr** [comment]
That's good to hear.

If you have any further scuffles with the Bezier.py code, please notify me.
And importantly, be sure to clone the proper repo if you are to clone at all:

    git clone https://git.sr.ht/~torresjrjr/Bezier.py

I may remove this GitHub repository.
